### PR TITLE
Support Additional Algorithms

### PR DESCRIPTION
**Pull request by AndrewPau**
Adding support for P384 and P521 curves

https://developers.yubico.com/YubiHSM2/Concepts/Algorithms.html

### CODE REVIEW

**Comment by AndrewPau** [comment]
Hi @hendrikhofstadt , would appreciate a review on this 2-liner whenever you get a chance 😄

**Comment by AndrewPau** [comment]
@leoluk would you be able to take a quick look at this 2-liner? Thanks!

**Comment by AndrewPau** [comment]
Bumping this, thanks!

**Comment by leoluk** [comment]
Thank you for your contribution!

**Pull request merged**
